In [1]:
import numpy as np
import pandas as pd

In [3]:
flats=pd.read_csv("C:\\Users\LENOVO\\OneDrive\\Desktop\\Machine learning project\\flats_cleaned.xls")
houses=pd.read_csv("C:\\Users\\LENOVO\\OneDrive\\Desktop\\Machine learning project\\house_cleaned.xls")

<>:1: SyntaxWarning: invalid escape sequence '\L'
<>:1: SyntaxWarning: invalid escape sequence '\L'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21272\4055256341.py:1: SyntaxWarning: invalid escape sequence '\L'
  flats=pd.read_csv("C:\\Users\LENOVO\\OneDrive\\Desktop\\Machine learning project\\flats_cleaned.xls")

In [5]:
flats.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1.0,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12.0,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2.0,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5.0,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [7]:
houses.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,not available,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3.0,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,house,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,not available,"Sector 21A Faridabad, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,house,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,not available,"Sushant Lok Phase 1, Gurgaon, Haryana",5.0,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,house,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,study room,"Sector 54 Gurgaon, Gurgaon, Haryana",5.0,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,house,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,study room,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5.0,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [9]:
df = pd.concat([flats,houses],ignore_index=True)

In [13]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
977,3 BHK Flat in Sector 83 Gurgaon,flat,vatika lifestyle homes,1.25,6839.0,1828.0,Super Built up area 1827.5(169.78 sq.m.),3,2,1,"servant room,study room,pooja room,store room","Tower 1, Sector 83 Gurgaon, Gurgaon, Haryana",6.0,South-West,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH – 08', 'Knowledge Tre...","Combination of low-Rise, mid-Rise, and high-Ri...","['1 Water Purifier', '1 Fridge', '7 Fan', '1 E...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction4 out ..."
2750,3 BHK Flat in Sector 85 Gurgaon,flat,godrej air,2.60,12212.0,2129.0,Built Up area: 2129 (197.79 sq.m.),3,3,3,servant room,"Sector 85, Sector 85 Gurgaon, Gurgaon, Haryana",17.0,NaN,Dec 2023,"['Sapphire 83 Mall', 'Sector 86 Road', 'Dwarka...",3bhk multistorey apartment for resale in godre...,NaN,NaN,"['Safety4.5 out of 5', 'Lifestyle5 out of 5', ..."
612,3 BHK Flat in Sector 37C Gurgaon,flat,imperia the esfera,0.99,5500.0,1800.0,Super Built up area 1815(168.62 sq.m.),3,3,1,servant room,"903, Sector 37C Gurgaon, Gurgaon, Haryana",10.0,North-East,0 to 1 Year Old,"['Approved Sector 37 Mero Station', 'Esplanade...",Its very nice budget friendly society,"['4 Fan', 'No AC', 'No Bed', 'No Chimney', 'No...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
3587,3 Bedroom House for sale in Sector 40 Gurgaon,house,independent,2.15,23889.0,(84 sq.m.) Plot Area,Plot area 100(83.61 sq.m.),3,3,3,servant room,"Sector 40 Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Huda city centre metro station', 'Axis bank ...",Its just behind ryan international school and ...,"['4 Wardrobe', '5 Fan', '4 Geyser', '2 Light',...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
923,2 BHK Flat in Sector 106 Gurgaon,flat,paras dews,0.97,8818.0,1100.0,Super Built up area 1385(128.67 sq.m.)Built Up...,2,2,3,pooja room,"1201, Sector 106 Gurgaon, Gurgaon, Haryana",6.0,North-East,0 to 1 Year Old,"['MG Road Metro Station', 'NeoSquare Shopping ...",Looking for a 2 bhk property for sale in gurga...,"['4 Fan', '1 Exhaust Fan', '1 Stove', '5 Light...","['Centrally Air Conditioned', 'Water purifier'...",NaN

In [15]:
#shuffling
df = df.sample(df.shape[0],ignore_index=True)

In [17]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 79 Gurgaon,flat,mapsko mount ville,1.30,8024.0,1620.0,Super Built up area 1620(150.5 sq.m.)Carpet ar...,3,3,2,"study room,pooja room","Sector 79 Gurgaon, Gurgaon, Haryana",6.0,West,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",This beautiful 3 bhk flat in sector 79 gurgaon...,"['6 Wardrobe', '1 Stove', '1 Chimney', '4 AC',...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
1,4 BHK Flat in Sector 112 Gurgaon,flat,experion windchants,5.20,10726.0,4848.0,Super Built up area 4848(450.39 sq.m.)Built Up...,4,6,3+,"servant room,pooja room","301, Sector 112 Gurgaon, Gurgaon, Haryana",15.0,East,1 to 5 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...",This 4 bhk apartment is available for sale in ...,"['6 Fan', '1 Exhaust Fan', '3 Geyser', '1 Stov...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
2,3 BHK Flat in Sohna,flat,signature global park,0.95,7846.0,1211.0,Built Up area: 1210.73 (112.48 sq.m.)Carpet ar...,3,2,3+,not available,"Sohna, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Sector 55-56 metro', 'Global city centre', '...","Low rise building, all amenities are available...",[],"['Security / Fire Alarm', 'Lift(s)', 'Swimming...","['Green Area5 out of 5', 'Amenities5 out of 5'..."
3,4 Bedroom House for sale in Nirvana Country,house,nirvana cedar crest,3.99,8866.0,(418 sq.m.) Plot Area,Plot area 4500(418.06 sq.m.),4,5,3+,servant room,"Nirvana Country, Gurgaon, Haryana",4.0,North-East,0 to 1 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",This is an newly constructed villa located in ...,"['4 Geyser', '9 Light', '1 AC', '1 Modular Kit...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
4,3 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,1.40,8861.0,1580.0,Super Built up area 1578(146.6 sq.m.),3,3,2,pooja room,"On Spr Road, Sector 69 Gurgaon, Gurgaon, Haryana",2.0,North-East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Tulip violet is one of the most popular destin...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4 out of..."

In [19]:
df.shape

(3961, 20)

In [ ]:
df.to_csv('gurgaon_properties.csv',index=False)